### ISSUE TITLE
Error in loading dynamic library

### ISSUE THREAD

**Issue by Tavpritesh** [wrathematics/pbdBASE#20]
Thanks for the great effort to make R scalable. However, on my CentOS 7 system, **the installation of pbdBASE fails in** _Error in dyn.load(file, DLLpath = DLLpath, ...) :  unable to load shared object '/home/centos/R/x86_64-unknown-linux-gnu-library/3.1/pbdBASE/libs/pbdBASE.so': /home/centos/R/x86_64-unknown-linux-gnu-library/3.1/pbdBASE/libs/pbdBASE.so: undefined symbol: lsame__

How can I resolve this issue. Thanks.

**Comment by alexvorobiev** [comment]
Are you using Revolution R? I also have this issue with RR. My guess is the error is caused by the fact that RR uses Intel MKL instead of BLAS so some additional compilation/linking options might be needed.

**Comment by wrathematics** [comment]
I'm unable to reproduce this.  Using the latest versions of RRO and MKL from MRAN, both the CRAN and (very buggy) development versions of pbdBASE install, load, and run fine.

The symbol is indeed present:

```
$ pwd
/usr/lib64/RRO-8.0.3/R-3.1.3/lib/R/lib
$ nm libRblas.so | grep lsame_
0000000000192440 T lapacke_lsame_
00000000000e8200 T lsame_
```

My Revo R is definitely using MKL, but even just checking the separate MKL files shows the same thing:

```
$ nm libmkl_rt.so | grep lsame_
0000000000192440 T lapacke_lsame_
00000000000e8200 T lsame_
```

**Comment by ehiggs** [comment]
I have a similar problem using icc/impi but my missing symbol is `pdtrmr2d_`. Also R 3.1.3.

**Comment by snoweye** [comment]
Please check if pbdSLAP installed correctly and what are the returns of next commands?
nm libslap.a | grep pdtrmr2d_

**Comment by ehiggs** [comment]
It's undefined as expected. 
```
$ nm R/x86_64-unknown-linux-gnu-library/3.1/pbdSLAP/lib/libslap.a | grep pdtrmr2d_
                 U pdtrmr2d_
```
I worked around it by hacking the pbdBASE configure script to link in SCALAPACK libraries. I guess pbdSLAP is a better place for this. Shall I open an issue for us to work through on pbdSLAP?

fwiw this is part of an effort in getting pbd* available in [EasyBuild](https://github.com/hpcugent/easybuild-easyconfigs)

**Comment by snoweye** [comment]
Well, you already have ScaLAPACK, then no need the pbdSLAP. I have no idea how it happens undefined in libslap.a unless GNU configure/make fails somewhere? Unfortunately, I don't have icc, impi, nor configure/make within EasyBuild.

**Comment by ehiggs** [comment]
I'll open a separate ticket instead of continuing to hijack this one.

**Comment by alexvorobiev** [comment]
I am still getting this error with MRO-3.2.4/MKL:

```
** testing if installed package can be loaded
--------------------------------------------------------------------------
[[33904,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: linux_host

Another transport will be used instead, although this may result in
lower performance.
--------------------------------------------------------------------------
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/path/to/library/pbdBASE/libs/pbdBASE.so':
  /path/to/library/pbdBASE/libs/pbdBASE.so: undefined symbol: lsame_
```

and I don't see that function in Rblas which came with MKL:

```
$ pwd
/opt/MRO-3.2.4/R-3.2.4/lib64/R/lib
$ nm libRblas.so | grep lsame_
$
```

On the other hand, i can see it in MKL:

```
$ for i in libmkl*.so;do echo $i;nm $i | grep lsame_; done
libmkl_core.so
libmkl_gf_ilp64.so
00000000000f55b0 T lsame_
libmkl_gf_lp64.so
00000000000f5b20 T lsame_
libmkl_gnu_thread.so
libmkl_vml_def.so
libmkl_vml_mc3.so
```

Is there any reason the package build process has a problem with that?
