### ISSUE TITLE
undefined symbol: lsame_

### ISSUE THREAD

**Issue by TheRichardLiu** [wrathematics/pbdBASE#21]
Dear author, 

I am using revolution R open and encountered such error.
May I know if any solution for this?	 

unable to load shared object '/.../R/library/pbdBASE/libs/pbdBASE.so':
	  .../R/library/pbdBASE/libs/pbdBASE.so: undefined symbol: lsame_

Thank you.

**Comment by wrathematics** [comment]
Thanks for the report.  This looks like a duplicate of this https://github.com/wrathematics/pbdBASE/issues/20

Closing this issue and working there.
